export type Rarity =
  | "common"
  | "uncommon"
  | "rare"
  | "mythical"
  | "legendary"
  | "immortal"
  | "arcana"
  | "ancient";

export type HeroAttribute = "strength" | "agility" | "intelligence" | "universal";

export const ATTRIBUTE_LABEL: Record<HeroAttribute, string> = {
  strength: "Fuerza",
  agility: "Agilidad",
  intelligence: "Inteligencia",
  universal: "Universal",
};

// Íconos oficiales de Dota 2 (cdn.steamstatic.com), autohospedados en /public/icons.
export const ATTRIBUTE_ICON: Record<HeroAttribute, string> = {
  strength: "/icons/hero_strength.png",
  agility: "/icons/hero_agility.png",
  intelligence: "/icons/hero_intelligence.png",
  universal: "/icons/hero_universal.png",
};

// Roster completo de héroes de Dota 2 (127), fuente: OpenDota API.
export const ALL_HERO_NAMES: string[] = [
  "Abaddon",
  "Alchemist",
  "Ancient Apparition",
  "Anti-Mage",
  "Arc Warden",
  "Axe",
  "Bane",
  "Batrider",
  "Beastmaster",
  "Bloodseeker",
  "Bounty Hunter",
  "Brewmaster",
  "Bristleback",
  "Broodmother",
  "Centaur Warrunner",
  "Chaos Knight",
  "Chen",
  "Clinkz",
  "Clockwerk",
  "Crystal Maiden",
  "Dark Seer",
  "Dark Willow",
  "Dawnbreaker",
  "Dazzle",
  "Death Prophet",
  "Disruptor",
  "Doom",
  "Dragon Knight",
  "Drow Ranger",
  "Earth Spirit",
  "Earthshaker",
  "Elder Titan",
  "Ember Spirit",
  "Enchantress",
  "Enigma",
  "Faceless Void",
  "Grimstroke",
  "Gyrocopter",
  "Hoodwink",
  "Huskar",
  "Invoker",
  "Io",
  "Jakiro",
  "Juggernaut",
  "Keeper of the Light",
  "Kez",
  "Kunkka",
  "Largo",
  "Legion Commander",
  "Leshrac",
  "Lich",
  "Lifestealer",
  "Lina",
  "Lion",
  "Lone Druid",
  "Luna",
  "Lycan",
  "Magnus",
  "Marci",
  "Mars",
  "Medusa",
  "Meepo",
  "Mirana",
  "Monkey King",
  "Morphling",
  "Muerta",
  "Naga Siren",
  "Nature's Prophet",
  "Necrophos",
  "Night Stalker",
  "Nyx Assassin",
  "Ogre Magi",
  "Omniknight",
  "Oracle",
  "Outworld Destroyer",
  "Pangolier",
  "Phantom Assassin",
  "Phantom Lancer",
  "Phoenix",
  "Primal Beast",
  "Puck",
  "Pudge",
  "Pugna",
  "Queen of Pain",
  "Razor",
  "Riki",
  "Ringmaster",
  "Rubick",
  "Sand King",
  "Shadow Demon",
  "Shadow Fiend",
  "Shadow Shaman",
  "Silencer",
  "Skywrath Mage",
  "Slardar",
  "Slark",
  "Snapfire",
  "Sniper",
  "Spectre",
  "Spirit Breaker",
  "Storm Spirit",
  "Sven",
  "Techies",
  "Templar Assassin",
  "Terrorblade",
  "Tidehunter",
  "Timbersaw",
  "Tinker",
  "Tiny",
  "Treant Protector",
  "Troll Warlord",
  "Tusk",
  "Underlord",
  "Undying",
  "Ursa",
  "Vengeful Spirit",
  "Venomancer",
  "Viper",
  "Visage",
  "Void Spirit",
  "Warlock",
  "Weaver",
  "Windranger",
  "Winter Wyvern",
  "Witch Doctor",
  "Wraith King",
  "Zeus",
];

// Atributo principal de cada héroe (clasificación oficial de Dota 2, vía OpenDota API).
export const HERO_ATTRIBUTE: Record<string, HeroAttribute> = {
  Abaddon: "universal",
  Alchemist: "strength",
  "Ancient Apparition": "intelligence",
  "Anti-Mage": "agility",
  "Arc Warden": "universal",
  Axe: "strength",
  Bane: "universal",
  Batrider: "universal",
  Beastmaster: "universal",
  Bloodseeker: "agility",
  "Bounty Hunter": "agility",
  Brewmaster: "universal",
  Bristleback: "strength",
  Broodmother: "agility",
  "Centaur Warrunner": "strength",
  "Chaos Knight": "strength",
  Chen: "intelligence",
  Clinkz: "agility",
  Clockwerk: "strength",
  "Crystal Maiden": "intelligence",
  "Dark Seer": "intelligence",
  "Dark Willow": "intelligence",
  Dawnbreaker: "strength",
  Dazzle: "universal",
  "Death Prophet": "universal",
  Disruptor: "intelligence",
  Doom: "strength",
  "Dragon Knight": "strength",
  "Drow Ranger": "agility",
  "Earth Spirit": "strength",
  Earthshaker: "strength",
  "Elder Titan": "strength",
  "Ember Spirit": "agility",
  Enchantress: "intelligence",
  Enigma: "universal",
  "Faceless Void": "agility",
  Grimstroke: "intelligence",
  Gyrocopter: "agility",
  Hoodwink: "agility",
  Huskar: "strength",
  Invoker: "intelligence",
  Io: "universal",
  Jakiro: "intelligence",
  Juggernaut: "agility",
  "Keeper of the Light": "intelligence",
  Kez: "agility",
  Kunkka: "strength",
  Largo: "strength",
  "Legion Commander": "strength",
  Leshrac: "intelligence",
  Lich: "intelligence",
  Lifestealer: "strength",
  Lina: "intelligence",
  Lion: "intelligence",
  "Lone Druid": "agility",
  Luna: "agility",
  Lycan: "strength",
  Magnus: "universal",
  Marci: "universal",
  Mars: "strength",
  Medusa: "agility",
  Meepo: "agility",
  Mirana: "agility",
  "Monkey King": "agility",
  Morphling: "agility",
  Muerta: "intelligence",
  "Naga Siren": "agility",
  "Nature's Prophet": "universal",
  Necrophos: "intelligence",
  "Night Stalker": "strength",
  "Nyx Assassin": "universal",
  "Ogre Magi": "strength",
  Omniknight: "strength",
  Oracle: "intelligence",
  "Outworld Destroyer": "intelligence",
  Pangolier: "universal",
  "Phantom Assassin": "agility",
  "Phantom Lancer": "agility",
  Phoenix: "strength",
  "Primal Beast": "strength",
  Puck: "intelligence",
  Pudge: "strength",
  Pugna: "intelligence",
  "Queen of Pain": "intelligence",
  Razor: "agility",
  Riki: "agility",
  Ringmaster: "intelligence",
  Rubick: "intelligence",
  "Sand King": "universal",
  "Shadow Demon": "intelligence",
  "Shadow Fiend": "agility",
  "Shadow Shaman": "intelligence",
  Silencer: "intelligence",
  "Skywrath Mage": "intelligence",
  Slardar: "strength",
  Slark: "agility",
  Snapfire: "universal",
  Sniper: "agility",
  Spectre: "agility",
  "Spirit Breaker": "strength",
  "Storm Spirit": "intelligence",
  Sven: "strength",
  Techies: "universal",
  "Templar Assassin": "agility",
  Terrorblade: "agility",
  Tidehunter: "strength",
  Timbersaw: "strength",
  Tinker: "intelligence",
  Tiny: "strength",
  "Treant Protector": "strength",
  "Troll Warlord": "agility",
  Tusk: "strength",
  Underlord: "strength",
  Undying: "strength",
  Ursa: "agility",
  "Vengeful Spirit": "agility",
  Venomancer: "universal",
  Viper: "agility",
  Visage: "universal",
  "Void Spirit": "universal",
  Warlock: "intelligence",
  Weaver: "agility",
  Windranger: "universal",
  "Winter Wyvern": "intelligence",
  "Witch Doctor": "intelligence",
  "Wraith King": "strength",
  Zeus: "intelligence",
};

// Ícono/retrato de cada héroe (autohospedado en /public/heroes, fuente: Dota 2 Fandom Wiki).
// Nota: Kez y Ringmaster (héroes muy recientes) todavía no tienen ícono en la wiki —
// caen al placeholder genérico hasta que se pueda descargar uno.
export const HERO_ICON: Record<string, string> = {
  Abaddon: "/heroes/abaddon.png",
  Alchemist: "/heroes/alchemist.png",
  "Ancient Apparition": "/heroes/ancient-apparition.png",
  "Anti-Mage": "/heroes/anti-mage.png",
  "Arc Warden": "/heroes/arc-warden.png",
  Axe: "/heroes/axe.png",
  Bane: "/heroes/bane.png",
  Batrider: "/heroes/batrider.png",
  Beastmaster: "/heroes/beastmaster.png",
  Bloodseeker: "/heroes/bloodseeker.png",
  "Bounty Hunter": "/heroes/bounty-hunter.png",
  Brewmaster: "/heroes/brewmaster.png",
  Bristleback: "/heroes/bristleback.png",
  Broodmother: "/heroes/broodmother.png",
  "Centaur Warrunner": "/heroes/centaur-warrunner.png",
  "Chaos Knight": "/heroes/chaos-knight.png",
  Chen: "/heroes/chen.png",
  Clinkz: "/heroes/clinkz.png",
  Clockwerk: "/heroes/clockwerk.png",
  "Crystal Maiden": "/heroes/crystal-maiden.png",
  "Dark Seer": "/heroes/dark-seer.png",
  "Dark Willow": "/heroes/dark-willow.png",
  Dawnbreaker: "/heroes/dawnbreaker.png",
  Dazzle: "/heroes/dazzle.png",
  "Death Prophet": "/heroes/death-prophet.png",
  Disruptor: "/heroes/disruptor.png",
  Doom: "/heroes/doom.png",
  "Dragon Knight": "/heroes/dragon-knight.png",
  "Drow Ranger": "/heroes/drow-ranger.png",
  "Earth Spirit": "/heroes/earth-spirit.png",
  Earthshaker: "/heroes/earthshaker.png",
  "Elder Titan": "/heroes/elder-titan.png",
  "Ember Spirit": "/heroes/ember-spirit.png",
  Enchantress: "/heroes/enchantress.png",
  Enigma: "/heroes/enigma.png",
  "Faceless Void": "/heroes/faceless-void.png",
  Grimstroke: "/heroes/grimstroke.png",
  Gyrocopter: "/heroes/gyrocopter.png",
  Hoodwink: "/heroes/hoodwink.png",
  Huskar: "/heroes/huskar.png",
  Invoker: "/heroes/invoker.png",
  Io: "/heroes/io.png",
  Jakiro: "/heroes/jakiro.png",
  Juggernaut: "/heroes/juggernaut.png",
  "Keeper of the Light": "/heroes/keeper-of-the-light.png",
  Kunkka: "/heroes/kunkka.png",
  "Legion Commander": "/heroes/legion-commander.png",
  Leshrac: "/heroes/leshrac.png",
  Lich: "/heroes/lich.png",
  Lifestealer: "/heroes/lifestealer.png",
  Lina: "/heroes/lina.png",
  Lion: "/heroes/lion.png",
  "Lone Druid": "/heroes/lone-druid.png",
  Luna: "/heroes/luna.png",
  Lycan: "/heroes/lycan.png",
  Magnus: "/heroes/magnus.png",
  Marci: "/heroes/marci.png",
  Mars: "/heroes/mars.png",
  Medusa: "/heroes/medusa.png",
  Meepo: "/heroes/meepo.png",
  Mirana: "/heroes/mirana.png",
  "Monkey King": "/heroes/monkey-king.png",
  Morphling: "/heroes/morphling.png",
  Muerta: "/heroes/muerta.png",
  "Naga Siren": "/heroes/naga-siren.png",
  "Nature's Prophet": "/heroes/natures-prophet.png",
  Necrophos: "/heroes/necrophos.png",
  "Night Stalker": "/heroes/night-stalker.png",
  "Nyx Assassin": "/heroes/nyx-assassin.png",
  "Ogre Magi": "/heroes/ogre-magi.png",
  Omniknight: "/heroes/omniknight.png",
  Oracle: "/heroes/oracle.png",
  "Outworld Destroyer": "/heroes/outworld-destroyer.png",
  Pangolier: "/heroes/pangolier.png",
  "Phantom Assassin": "/heroes/phantom-assassin.png",
  "Phantom Lancer": "/heroes/phantom-lancer.png",
  Phoenix: "/heroes/phoenix.png",
  "Primal Beast": "/heroes/primal-beast.png",
  Puck: "/heroes/puck.png",
  Pudge: "/heroes/pudge.png",
  Pugna: "/heroes/pugna.png",
  "Queen of Pain": "/heroes/queen-of-pain.png",
  Razor: "/heroes/razor.png",
  Riki: "/heroes/riki.png",
  Rubick: "/heroes/rubick.png",
  "Sand King": "/heroes/sand-king.png",
  "Shadow Demon": "/heroes/shadow-demon.png",
  "Shadow Fiend": "/heroes/shadow-fiend.png",
  "Shadow Shaman": "/heroes/shadow-shaman.png",
  Silencer: "/heroes/silencer.png",
  "Skywrath Mage": "/heroes/skywrath-mage.png",
  Slardar: "/heroes/slardar.png",
  Slark: "/heroes/slark.png",
  Snapfire: "/heroes/snapfire.png",
  Sniper: "/heroes/sniper.png",
  Spectre: "/heroes/spectre.png",
  "Spirit Breaker": "/heroes/spirit-breaker.png",
  "Storm Spirit": "/heroes/storm-spirit.png",
  Sven: "/heroes/sven.png",
  Techies: "/heroes/techies.png",
  "Templar Assassin": "/heroes/templar-assassin.png",
  Terrorblade: "/heroes/terrorblade.png",
  Tidehunter: "/heroes/tidehunter.png",
  Timbersaw: "/heroes/timbersaw.png",
  Tinker: "/heroes/tinker.png",
  Tiny: "/heroes/tiny.png",
  "Treant Protector": "/heroes/treant-protector.png",
  "Troll Warlord": "/heroes/troll-warlord.png",
  Tusk: "/heroes/tusk.png",
  Underlord: "/heroes/underlord.png",
  Undying: "/heroes/undying.png",
  Ursa: "/heroes/ursa.png",
  "Vengeful Spirit": "/heroes/vengeful-spirit.png",
  Venomancer: "/heroes/venomancer.png",
  Viper: "/heroes/viper.png",
  Visage: "/heroes/visage.png",
  "Void Spirit": "/heroes/void-spirit.png",
  Warlock: "/heroes/warlock.png",
  Weaver: "/heroes/weaver.png",
  Windranger: "/heroes/windranger.png",
  "Winter Wyvern": "/heroes/winter-wyvern.png",
  "Witch Doctor": "/heroes/witch-doctor.png",
  "Wraith King": "/heroes/wraith-king.png",
  Zeus: "/heroes/zeus.png",
};

export type ItemCategory = "hero" | "courier" | "weather" | "treasure";

export const CATEGORY_LABEL: Record<ItemCategory, string> = {
  hero: "Item de Héroe",
  courier: "Courier",
  weather: "Clima",
  treasure: "Items Cache",
};

export interface DotaItem {
  id: string;
  name: string;
  /** Héroe dueño del cosmético. No aplica a couriers ni climas (son universales). */
  hero?: string;
  category: ItemCategory;
  rarity: Rarity;
  /** Precio de referencia tomado del Steam Market (S/) */
  marketPrice: number;
  /** Precio final de venta al público, ya con el markup de la empresa aplicado (S/) */
  price: number;
  /** Precio que la empresa paga al usuario si decide vender este item (S/) */
  buybackPrice: number;
  imageLabel: string;
  /** Fecha en que se publicó el item en la tienda (ISO, YYYY-MM-DD) */
  dateAdded: string;
}

/** Texto a mostrar como subtítulo del item: el héroe si aplica, o su categoría. */
export function itemSubtitle(item: DotaItem): string {
  return item.hero ?? CATEGORY_LABEL[item.category];
}

// Rareza oficial de Dota 2 (8 niveles). Los colores corresponden a los
// definidos por Valve para cada rareza, no a una elección de diseño libre.
export const RARITY_LABEL: Record<Rarity, string> = {
  common: "Común",
  uncommon: "Poco Común",
  rare: "Raro",
  mythical: "Mítico",
  legendary: "Legendario",
  immortal: "Inmortal",
  arcana: "Arcano",
  ancient: "Anciano",
};

export const RARITY_CLASS: Record<Rarity, string> = {
  common: "rarity-common",
  uncommon: "rarity-uncommon",
  rare: "rarity-rare",
  mythical: "rarity-mythical",
  legendary: "rarity-legendary",
  immortal: "rarity-immortal",
  arcana: "rarity-arcana",
  ancient: "rarity-ancient",
};

export const RARITY_TEXT_CLASS: Record<Rarity, string> = {
  common: "text-rarity-common",
  uncommon: "text-rarity-uncommon",
  rare: "text-rarity-rare",
  mythical: "text-rarity-mythical",
  legendary: "text-rarity-legendary",
  immortal: "text-rarity-immortal",
  arcana: "text-rarity-arcana",
  ancient: "text-rarity-ancient",
};

export const RARITY_BADGE_CLASS: Record<Rarity, string> = {
  common: "bg-rarity-common/10 text-rarity-common border border-rarity-common/20",
  uncommon: "bg-rarity-uncommon/10 text-rarity-uncommon border border-rarity-uncommon/20",
  rare: "bg-rarity-rare/10 text-rarity-rare border border-rarity-rare/20",
  mythical: "bg-rarity-mythical/10 text-rarity-mythical border border-rarity-mythical/20",
  legendary: "bg-rarity-legendary/10 text-rarity-legendary border border-rarity-legendary/20",
  immortal: "bg-rarity-immortal/10 text-rarity-immortal border border-rarity-immortal/20",
  arcana: "bg-rarity-arcana/10 text-rarity-arcana border border-rarity-arcana/20",
  ancient: "bg-rarity-ancient/10 text-rarity-ancient border border-rarity-ancient/20",
};

// Datos de ejemplo — reemplazar más adelante por los datos reales
// sincronizados desde la API del Steam Market.
export const ITEMS: DotaItem[] = [
  {
    id: "manifold-paradox",
    name: "Paradoja del Manifold",
    hero: "Phantom Assassin",
    category: "hero",
    rarity: "arcana",
    marketPrice: 620,
    price: 745,
    buybackPrice: 520,
    imageLabel: "Arcana Phantom Assassin",
    dateAdded: "2026-06-02",
  },
  {
    id: "golden-basher",
    name: "Guanteletes Dorados del Basher",
    hero: "Anti-Mage",
    category: "hero",
    rarity: "immortal",
    marketPrice: 310,
    price: 372,
    buybackPrice: 260,
    imageLabel: "Inmortal Anti-Mage",
    dateAdded: "2026-06-05",
  },
  {
    id: "feast-abscession",
    name: "Festín de la Abscesión",
    hero: "Pudge",
    category: "hero",
    rarity: "arcana",
    marketPrice: 580,
    price: 696,
    buybackPrice: 486,
    imageLabel: "Arcana Pudge",
    dateAdded: "2026-06-09",
  },
  {
    id: "dragonclaw-hook",
    name: "Gancho Garra de Dragón",
    hero: "Pudge",
    category: "hero",
    rarity: "immortal",
    marketPrice: 1050,
    price: 1260,
    buybackPrice: 882,
    imageLabel: "Inmortal Pudge",
    dateAdded: "2026-06-12",
  },
  {
    id: "faceless-void-arcana",
    name: "Guardián del Vacío Eterno",
    hero: "Faceless Void",
    category: "hero",
    rarity: "mythical",
    marketPrice: 145,
    price: 174,
    buybackPrice: 122,
    imageLabel: "Mítico Faceless Void",
    dateAdded: "2026-06-16",
  },
  {
    id: "crimson-witness",
    name: "Testigo Carmesí",
    hero: "Terrorblade",
    category: "hero",
    rarity: "legendary",
    marketPrice: 210,
    price: 252,
    buybackPrice: 176,
    imageLabel: "Legendario Terrorblade",
    dateAdded: "2026-06-19",
  },
  {
    id: "frostivus-set",
    name: "Set Corona de Escarcha",
    hero: "Crystal Maiden",
    category: "hero",
    rarity: "mythical",
    marketPrice: 95,
    price: 114,
    buybackPrice: 80,
    imageLabel: "Mítico Crystal Maiden",
    dateAdded: "2026-06-23",
  },
  {
    id: "swordmaster-arcana",
    name: "Maestro de la Hoja Eterna",
    hero: "Juggernaut",
    category: "hero",
    rarity: "arcana",
    marketPrice: 540,
    price: 648,
    buybackPrice: 453,
    imageLabel: "Arcana Juggernaut",
    dateAdded: "2026-06-26",
  },
  {
    id: "wanderers-cloak",
    name: "Capa del Errante",
    hero: "Bounty Hunter",
    category: "hero",
    rarity: "common",
    marketPrice: 8,
    price: 10,
    buybackPrice: 7,
    imageLabel: "Común Bounty Hunter",
    dateAdded: "2026-06-30",
  },
  {
    id: "ember-guard-helm",
    name: "Yelmo de la Guardia de Brasas",
    hero: "Ember Spirit",
    category: "hero",
    rarity: "uncommon",
    marketPrice: 18,
    price: 22,
    buybackPrice: 15,
    imageLabel: "Poco Común Ember Spirit",
    dateAdded: "2026-07-03",
  },
  {
    id: "stonebreaker-axe",
    name: "Hacha Quebrantapiedras",
    hero: "Sven",
    category: "hero",
    rarity: "rare",
    marketPrice: 38,
    price: 46,
    buybackPrice: 32,
    imageLabel: "Raro Sven",
    dateAdded: "2026-07-07",
  },
  {
    id: "ancient-wyrm-armor",
    name: "Armadura del Wyrm Ancestral",
    hero: "Dragon Knight",
    category: "hero",
    rarity: "ancient",
    marketPrice: 890,
    price: 1068,
    buybackPrice: 747,
    imageLabel: "Anciano Dragon Knight",
    dateAdded: "2026-07-10",
  },
  {
    id: "spider-feather-courier",
    name: "Correo Araña Emplumada",
    category: "courier",
    rarity: "mythical",
    marketPrice: 62,
    price: 74,
    buybackPrice: 52,
    imageLabel: "Courier Araña Emplumada",
    dateAdded: "2026-07-22",
  },
  {
    id: "baby-roshan-courier",
    name: "Bebé Roshan",
    category: "courier",
    rarity: "immortal",
    marketPrice: 185,
    price: 222,
    buybackPrice: 155,
    imageLabel: "Courier Bebé Roshan",
    dateAdded: "2026-07-24",
  },
  {
    id: "autumn-frost-weather",
    name: "Escarcha de Otoño",
    category: "weather",
    rarity: "rare",
    marketPrice: 25,
    price: 30,
    buybackPrice: 21,
    imageLabel: "Clima Escarcha de Otoño",
    dateAdded: "2026-07-26",
  },
  {
    id: "ashen-sandstorm-weather",
    name: "Tormenta de Arena Cenicienta",
    category: "weather",
    rarity: "legendary",
    marketPrice: 88,
    price: 106,
    buybackPrice: 74,
    imageLabel: "Clima Tormenta de Arena Cenicienta",
    dateAdded: "2026-07-27",
  },
];

export type OrderStatus = "pendiente" | "procesado" | "rechazado";

export interface SaleOrder {
  id: string;
  userName: string;
  date: string;
  items: DotaItem[];
  total: number;
  tradeUrl: string;
  status: OrderStatus;
}

export const ORDERS: SaleOrder[] = [
  {
    id: "order-1",
    userName: "Liquid_Nisha",
    date: "27 Jul 2026 · 14:22",
    items: [ITEMS[1], ITEMS[4], ITEMS[6]],
    total: ITEMS[1].buybackPrice + ITEMS[4].buybackPrice + ITEMS[6].buybackPrice,
    tradeUrl: "https://steamcommunity.com/tradeoffer/new/?partner=123456789&token=AbCdEfGh",
    status: "pendiente",
  },
  {
    id: "order-2",
    userName: "Arteezy_2nd",
    date: "27 Jul 2026 · 12:05",
    items: [ITEMS[3]],
    total: ITEMS[3].buybackPrice,
    tradeUrl: "https://steamcommunity.com/tradeoffer/new/?partner=987654321&token=WxYzAbCd",
    status: "procesado",
  },
  {
    id: "order-3",
    userName: "Miracle_Fan99",
    date: "26 Jul 2026 · 20:40",
    items: [ITEMS[0], ITEMS[7]],
    total: ITEMS[0].buybackPrice + ITEMS[7].buybackPrice,
    tradeUrl: "https://steamcommunity.com/tradeoffer/new/?partner=112233445&token=IjKlMnOp",
    status: "pendiente",
  },
];
