import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-container": "#cbc8c8",
        "on-surface-variant": "#e4beb7",
        "surface-dim": "#131313",
        "tertiary-fixed-dim": "#c8c6c5",
        "surface-tint": "#ffb4a6",
        "surface-container-low": "#1c1b1b",
        "surface-container": "#201f1f",
        "surface-container-lowest": "#0e0e0e",
        "on-surface": "#e5e2e1",
        "on-secondary-container": "#342800",
        "tertiary-container": "#555454",
        "surface-bright": "#3a3939",
        "on-tertiary-fixed": "#1c1b1b",
        surface: "#131313",
        "tertiary-fixed": "#e5e2e1",
        "on-primary-container": "#ffb7aa",
        "surface-container-highest": "#353534",
        "on-secondary": "#3c2f00",
        "inverse-primary": "#b81f0c",
        primary: "#ffb4a6",
        "on-tertiary-fixed-variant": "#474646",
        "secondary-container": "#af8d11",
        "surface-container-high": "#2a2a2a",
        tertiary: "#c8c6c5",
        outline: "#ab8983",
        "inverse-on-surface": "#313030",
        "on-primary": "#670600",
        "on-primary-fixed": "#400200",
        "primary-container": "#a91101",
        error: "#ffb4ab",
        "outline-variant": "#5b403b",
        secondary: "#e9c349",
        "on-secondary-fixed": "#241a00",
        "on-primary-fixed-variant": "#910c00",
        "on-secondary-fixed-variant": "#574500",
        "on-background": "#e5e2e1",
        background: "#0A0A0A",
        "secondary-fixed": "#ffe088",
        "primary-fixed": "#ffdad4",
        "primary-fixed-dim": "#ffb4a6",
        "error-container": "#93000a",
        "surface-variant": "#353534",
        "on-tertiary": "#313030",
        "inverse-surface": "#e5e2e1",
        "on-error-container": "#ffdad6",
        "secondary-fixed-dim": "#e9c349",
        "on-error": "#690005",
        "rarity-common": "#B0C3D9",
        "rarity-uncommon": "#5E98D9",
        "rarity-rare": "#4B69FF",
        "rarity-mythical": "#8847FF",
        "rarity-legendary": "#D32CE6",
        "rarity-immortal": "#E4AE39",
        "rarity-arcana": "#ADE55C",
        "rarity-ancient": "#EB4B4B",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.125rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "margin-mobile": "16px",
        "margin-desktop": "64px",
        base: "8px",
        "container-max": "1440px",
        gutter: "24px",
      },
      fontFamily: {
        "headline-md": ["Montserrat", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "price-display": ["Montserrat", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
        "headline-xl": ["Montserrat", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Montserrat", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "label-caps": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "price-display": ["20px", { lineHeight: "24px", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-xl": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
      },
    },
  },
  plugins: [],
};

export default config;
